// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace HomePit.Infrastructure.Migrations
{
    partial class AddHouseholdInvitations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            var snapshot = new HomePitDbContextModelSnapshot();
            var buildModel = typeof(HomePitDbContextModelSnapshot).GetMethod(
                "BuildModel",
                BindingFlags.Instance | BindingFlags.NonPublic);

            if (buildModel is null)
            {
                throw new MissingMethodException(
                    typeof(HomePitDbContextModelSnapshot).FullName,
                    "BuildModel");
            }

            buildModel.Invoke(snapshot, new object[] { modelBuilder });
        }
    }
}
