// <auto-generated />
using System;
using System.Reflection;
using HomePit.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HomePit.Infrastructure.Migrations
{
    [DbContext(typeof(HomePitDbContext))]
    [Migration("20260713160000_AddMemberEffortAllocations")]
    partial class AddMemberEffortAllocations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            var snapshot = new HomePitDbContextModelSnapshot();
            var buildModel = typeof(HomePitDbContextModelSnapshot).GetMethod(
                "BuildModel",
                BindingFlags.Instance | BindingFlags.NonPublic);

            if (buildModel is null)
            {
                throw new MissingMethodException(
                    typeof(HomePitDbContextModelSnapshot).FullName,
                    "BuildModel");
            }

            buildModel.Invoke(snapshot, new object[] { modelBuilder });
        }
    }
}
